config/routes.rb
Rails.application.routes.draw do
  resources :grades
  root 'grades#index'
  

end

app/models/grade.rb
class Grade < ActiveRecord::Base
      validates :Mark, presence: true, allow_nil: false, numericality: {greater_than_or_equal_to: 0 }
      validates :MarkOutOf, presence: true, allow_nil: false, numericality: {greater_than: 0 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/grades_controller.rb
class GradesController < ApplicationController
  before_action :set_grade, only: [:show, :edit, :update, :destroy]

  # GET /grades
  # GET /grades.json
  def index
    @grades = Grade.all
  end

  # GET /grades/1
  # GET /grades/1.json
  def show
    @grade = Grade.find(params[:id])
  end

  # GET /grades/new
  def new
    @grade = Grade.new
  end

  # GET /grades/1/edit
  def edit
    @grade = Grade.find(params[:id])
  end

  # POST /grades
  # POST /grades.json
  def create
    @grade = Grade.new(grade_params)

    respond_to do |format|
      if @grade.save
        format.html { redirect_to @grade, notice: 'Grade was successfully created.' }
        format.json { render :show, status: :created, location: @grade }
      else
        format.html { render :new }
        format.json { render json: @grade.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /grades/1
  # PATCH/PUT /grades/1.json
  def update
    respond_to do |format|
      if @grade.update_attributes(grade_params)
        format.html { redirect_to grades_path }
        format.json { render :show, status: :ok, location: @grade }
      else
        format.html { render :edit }
        format.json { render json: @grade.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /grades/1
  # DELETE /grades/1.json
  def destroy
    @grade.destroy
    respond_to do |format|
      format.html { redirect_to grades_path }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_grade
      @grade = Grade.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def grade_params
      params.require(:grade).permit(:Mark, :MarkOutOf)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/grades_helper.rb
module GradesHelper
end

app/views/grades/_form.html.erb
<%= form_for(@grade) do |f| %>
  <% if @grade.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@grade.errors.count, "error") %> prohibited this grade from being saved:</h2>

      <ul>
      <% @grade.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Mark %><br>
    <%= f.text_field :Mark, class: 'form-control'%>
  </div>
  <div class="field">
    <%= f.label :'Out of' %><br>
    <%= f.text_field :MarkOutOf, class: 'form-control' %>
  </div>
  <div class="actions">
    <%= f.submit "Update Grade", class: "btn btn-primary"%>
  </div>
<% end %>

app/views/grades/edit.html.erb
<h1>Fix this Grade</h1>

<%= render 'form' %>


<%= link_to 'Cancel', grades_path %>

app/views/grades/index.html.erb
<!DOCTYPE html>
<html>
  
<head>
<link rel="stylesheet" type="text/css" href="grades.css">
<script src="calculator.js">
</script>


</head>

  <body>

  
  <p id="notice"><%= notice %></p>

<section>
  <h1>Grade Calculator</h1>


<div>
<h3>Activities</h3>

<p>Give grades to the numeric activities:</p>

 

<table style="width:100%">
  <thead>
    <tr>
      <th>Name</th>
      <th>Short Name</th>
      <th>Grade</th>
      <th>Percentage</th>
      
    </tr>
  </thead>



  <tbody>
    
    <% @grades.each do |grade| %>
      <tr>
        <td>Activity <%= grade.id %></td>
        <td>A<%= grade.id %></td>
        <td><%= grade.Mark %> / <%= grade.MarkOutOf %></td>
        <td><%= 100*grade.Mark/[grade.MarkOutOf,1].max %>%</td>
        <td id=fix><%= link_to 'Fix Grade', edit_grade_path(grade) %> | <%= link_to 'Remove Activity', grade, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
     <tr>
      <td><b>TOTAL</b></td>
      <td colspan="1"></td>
      <td colspan="1"></td>
      <b><td id="result" colspan="1"></td></b>
    </tr>
  </tbody>
</table>

<script>countActivities=0;</script>
<% @grades.each do |grade| %>
  <script>countActivities += 1;</script>
<% end %>

<script>
meanOfGrades=0;
averageOfGradesNumerator=0;
averageOfGradesDenominator=0;
averageOfGrades=0;
</script>
<% @grades.each do |grade| %>
<script>
var num = <%= grade.Mark %>;
var den = <%= grade.MarkOutOf %>
averageOfGradesNumerator += num;
  averageOfGradesDenominator += den;
  
  meanOfGrades += <%= grade.Mark/[grade.MarkOutOf,1].max %>;
  
  </script>
<% end %>
<script>meanOfGrades=getPercentage(meanOfGrades,countActivities);
averageOfGrades=getPercentage(averageOfGradesNumerator,averageOfGradesDenominator);</script>


<br>
<%= link_to 'Add an Activity', new_grade_path %>

<br>


<p align="center">
<button type="button" onclick="AVERAGE()">AVERAGE</button></button>
<button type="button" onclick="MEAN()">MEAN</button></button>
</p>



<a href="http://www.lib.sfu.ca/about/branches-depts/slc/learning/exam-prep/efficient-effective-study">Useful study tips</a>


</div>
</section>

</body>
</html>

app/views/grades/new.html.erb
<h1>New Activity Grade</h1>

<%= render 'form' %>

<%= link_to 'Back', grades_path %>

app/views/grades/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Mark:</strong>
  <%= @grade.Mark %>
</p>

<p>
  <strong>Markoutof:</strong>
  <%= @grade.MarkOutOf %>
</p>

<%= link_to 'Edit', edit_grade_path(@grade) %> |
<%= link_to 'Back', grades_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Grade Calculator</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>